CREATE TABLE IF NOT EXISTS `#__pizzza` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT
  , `catid` INT(11) UNSIGNED NOT NULL COMMENT 'Category ID'
  , `checked_out` INT(11) UNSIGNED NOT NULL
  , `title` VARCHAR(150) NOT NULL

  , PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
